name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 30
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHP${{ matrix.php }}-${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis, fileinfo
          coverage: none

      - name: Change composer requirement for PHP 8.1+
        run: composer require phpunit/phpunit:9.5.10 --dev --no-update --no-interaction
        if: matrix.php == "8.1" && matrix.stability == 'prefer-lowest'

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit
